sudo: required
language: python

cache:
  directories:
    - /tmp/travis-cache

matrix:
  # List of environment combinations to test against.
  # https://zato.io/docs/admin/guide/install/index.html#operating-system-considerations
  include:
    - os: osx
      env: MODE=packaging IMAGE=
    - os: linux
      env: MODE=packaging IMAGE=ubuntu:14.04
    - os: linux
      env: MODE=packaging IMAGE=centos:6
    - os: linux
      env: MODE=packaging IMAGE=centos:7
    - os: linux
      env: MODE=packaging IMAGE=ubuntu:12.04
    - os: linux
      env: MODE=packaging IMAGE=i386/ubuntu:14.04
    - os: linux
      env: MODE=packaging IMAGE=ubuntu:16.04
    - os: linux
      env: MODE=packaging IMAGE=debian:7
    - os: linux
      env: MODE=packaging IMAGE=debian:8
    - os: linux
      env: MODE=packaging IMAGE=debian:9
    - os: linux
      env: MODE=packaging IMAGE=alpine:3.7
  allow_failures:
    # Don't fail the build for a problem with OS X
    - osx

notifications:
  email: false

script:
  - source .travis/test_${MODE}.sh
