"""state_as_of_411a1ddb

Revision ID: 934259d2a3b7
Revises: 0028_ae3419a9
Create Date: 2017-12-14 15:12:56.817799

"""

# Revision identifiers, used by Alembic.
revision = '0028a_934259d2a3b7'
down_revision = '0028_ae3419a9'

from alembic import context, op
import sqlalchemy as sa

# Zato
from zato.common.odb import model

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
