"""migrate_from_411a1ddb_to_5a7b9403

Revision ID: 00ad4c118b99
Revises: 0028a_934259d2a3b7
Create Date: 2017-12-14 15:29:40.477831

"""

# Revision identifiers, used by Alembic.
revision = '0029a_00ad4c118b99'
down_revision = '0028a_934259d2a3b7'

from alembic import context, op
import sqlalchemy as sa

# Zato
from zato.common.odb import model

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('cache_type', sa.String(length=45), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('cache_memcached',
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('servers', sa.Text(), nullable=False),
    sa.Column('is_debug', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.LargeBinary(length=20000), nullable=True),
    sa.ForeignKeyConstraint(['cache_id'], [u'cache.id'], ),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_table('cache_builtin',
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('max_item_size', sa.Integer(), nullable=False),
    sa.Column('extend_expiry_on_get', sa.Boolean(), nullable=False),
    sa.Column('extend_expiry_on_set', sa.Boolean(), nullable=False),
    sa.Column('sync_method', sa.String(length=20), nullable=False),
    sa.Column('persistent_storage', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['cache_id'], [u'cache.id'], ),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_table('pubsub_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('last_pub_time', sa.BigInteger(), nullable=True),
    sa.Column('max_depth_gd', sa.Integer(), nullable=False),
    sa.Column('max_depth_non_gd', sa.Integer(), nullable=False),
    sa.Column('current_depth_gd', sa.Integer(), nullable=False),
    sa.Column('gd_depth_check_freq', sa.Integer(), nullable=False),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('is_api_sub_allowed', sa.Boolean(), nullable=False),
    sa.Column('hook_service_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['hook_service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_tp_clust_idx', 'pubsub_topic', ['cluster_id'], unique=False)
    op.create_index('pubsb_tp_id_idx', 'pubsub_topic', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_tp_name_idx', 'pubsub_topic', ['cluster_id', 'name'], unique=True)
    op.create_table('pubsub_endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('endpoint_type', sa.String(length=40), nullable=False),
    sa.Column('last_seen', sa.BigInteger(), nullable=True),
    sa.Column('last_pub_time', sa.BigInteger(), nullable=True),
    sa.Column('last_sub_time', sa.BigInteger(), nullable=True),
    sa.Column('last_deliv_time', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('topic_patterns', sa.Text(), nullable=True),
    sa.Column('pub_tag_patterns', sa.Text(), nullable=True),
    sa.Column('message_tag_patterns', sa.Text(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('ws_channel_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], [u'sec_base.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['ws_channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'name'),
    sa.UniqueConstraint('cluster_id', 'security_id'),
    sa.UniqueConstraint('cluster_id', 'service_id'),
    sa.UniqueConstraint('cluster_id', 'ws_channel_id')
    )
    op.create_index('pubsb_endp_clust_idx', 'pubsub_endpoint', ['cluster_id'], unique=False)
    op.create_index('pubsb_endp_id_idx', 'pubsub_endpoint', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_endp_name_idx', 'pubsub_endpoint', ['cluster_id', 'name'], unique=True)
    op.create_table('web_socket_cli_ps_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_key', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], [u'web_socket_client.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('wscl_psk_cli', 'web_socket_cli_ps_keys', ['cluster_id', 'client_id'], unique=False)
    op.create_index('wscl_psk_sk', 'web_socket_cli_ps_keys', ['cluster_id', 'sub_key'], unique=False)
    op.create_table('pubsub_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_msg_id', sa.String(length=200), nullable=False),
    sa.Column('pub_correl_id', sa.String(length=200), nullable=True),
    sa.Column('in_reply_to', sa.String(length=200), nullable=True),
    sa.Column('ext_client_id', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('position_in_group', sa.Integer(), nullable=True),
    sa.Column('pattern_matched', sa.Text(), nullable=False),
    sa.Column('pub_time', sa.BigInteger(), nullable=False),
    sa.Column('ext_pub_time', sa.BigInteger(), nullable=True),
    sa.Column('expiration_time', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('data_prefix', sa.Text(), nullable=False),
    sa.Column('data_prefix_short', sa.String(length=200), nullable=False),
    sa.Column('data_format', sa.String(length=200), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.Integer(), nullable=False),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('published_by_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_msg_id_idx', 'pubsub_message', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_msg_inreplyto_id_idx', 'pubsub_message', ['cluster_id', 'in_reply_to'], unique=False)
    op.create_index('pubsb_msg_pubmsg_id_idx', 'pubsub_message', ['cluster_id', 'pub_msg_id'], unique=True)
    op.create_table('pubsub_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.Column('sub_key', sa.String(length=200), nullable=False),
    sa.Column('pattern_matched', sa.Text(), nullable=False),
    sa.Column('deliver_by', sa.Text(), nullable=True),
    sa.Column('ext_client_id', sa.Text(), nullable=True),
    sa.Column('is_durable', sa.Boolean(), nullable=False),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('active_status', sa.String(length=200), nullable=False),
    sa.Column('is_staging_enabled', sa.Boolean(), nullable=False),
    sa.Column('delivery_method', sa.String(length=200), nullable=False),
    sa.Column('delivery_data_format', sa.String(length=200), nullable=False),
    sa.Column('delivery_endpoint', sa.Text(), nullable=True),
    sa.Column('last_interaction_time', sa.BigInteger(), nullable=True),
    sa.Column('last_interaction_type', sa.String(length=200), nullable=True),
    sa.Column('last_interaction_details', sa.Text(), nullable=True),
    sa.Column('delivery_batch_size', sa.Integer(), nullable=False),
    sa.Column('wrap_one_msg_in_list', sa.Boolean(), nullable=False),
    sa.Column('delivery_max_size', sa.Integer(), nullable=False),
    sa.Column('delivery_max_retry', sa.Integer(), nullable=False),
    sa.Column('delivery_err_should_block', sa.Boolean(), nullable=False),
    sa.Column('wait_sock_err', sa.Integer(), nullable=False),
    sa.Column('wait_non_sock_err', sa.Integer(), nullable=False),
    sa.Column('hook_service_id', sa.Integer(), nullable=True),
    sa.Column('out_http_method', sa.Text(), nullable=True),
    sa.Column('amqp_exchange', sa.Text(), nullable=True),
    sa.Column('amqp_routing_key', sa.Text(), nullable=True),
    sa.Column('files_directory_list', sa.Text(), nullable=True),
    sa.Column('ftp_directory_list', sa.Text(), nullable=True),
    sa.Column('sms_twilio_from', sa.Text(), nullable=True),
    sa.Column('sms_twilio_to_list', sa.Text(), nullable=True),
    sa.Column('smtp_subject', sa.Text(), nullable=True),
    sa.Column('smtp_from', sa.Text(), nullable=True),
    sa.Column('smtp_to_list', sa.Text(), nullable=True),
    sa.Column('smtp_body', sa.Text(), nullable=True),
    sa.Column('smtp_is_html', sa.Boolean(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('out_job_id', sa.Integer(), nullable=True),
    sa.Column('out_http_soap_id', sa.Integer(), nullable=True),
    sa.Column('out_smtp_id', sa.Integer(), nullable=True),
    sa.Column('out_amqp_id', sa.Integer(), nullable=True),
    sa.Column('ws_sub_id', sa.Integer(), nullable=True),
    sa.Column('ws_channel_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['hook_service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_amqp_id'], [u'out_amqp.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_http_soap_id'], [u'http_soap.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_job_id'], [u'job.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_smtp_id'], [u'email_smtp.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], [u'server.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['ws_channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['ws_sub_id'], [u'web_socket_sub.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_sub_clust_endpt_idx', 'pubsub_sub', ['cluster_id', 'endpoint_id', 'topic_id'], unique=False)
    op.create_index('pubsb_sub_clust_idx', 'pubsub_sub', ['cluster_id'], unique=False)
    op.create_index('pubsb_sub_clust_subk', 'pubsub_sub', ['cluster_id', 'sub_key'], unique=True)
    op.create_index('pubsb_sub_id_idx', 'pubsub_sub', ['cluster_id', 'id'], unique=True)
    op.create_table('pubsub_endp_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_matched', sa.Text(), nullable=False),
    sa.Column('last_pub_time', sa.BigInteger(), nullable=False),
    sa.Column('pub_msg_id', sa.String(length=200), nullable=False),
    sa.Column('pub_correl_id', sa.String(length=200), nullable=True),
    sa.Column('in_reply_to', sa.String(length=200), nullable=True),
    sa.Column('ext_client_id', sa.Text(), nullable=True),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_endpt_clsendtp_idx', 'pubsub_endp_topic', ['cluster_id', 'endpoint_id', 'topic_id'], unique=True)
    op.create_index('pubsb_endpt_clust_idx', 'pubsub_endp_topic', ['cluster_id'], unique=False)
    op.create_index('pubsb_endpt_id_idx', 'pubsub_endp_topic', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_endpt_msgid_idx', 'pubsub_endp_topic', ['cluster_id', 'pub_msg_id'], unique=True)
    op.create_table('pubsub_endp_msg_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('last_delivery_time', sa.BigInteger(), nullable=True),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('is_in_staging', sa.Boolean(), nullable=False),
    sa.Column('is_deliverable', sa.Boolean(), nullable=False),
    sa.Column('delivery_status', sa.Text(), nullable=False),
    sa.Column('delivery_time', sa.BigInteger(), nullable=True),
    sa.Column('pub_msg_id', sa.String(length=200), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['pub_msg_id'], [u'pubsub_message.pub_msg_id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], [u'pubsub_sub.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_enms_q_endp_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'endpoint_id'], unique=False)
    op.create_index('pubsb_enms_q_endptp_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'endpoint_id', 'topic_id'], unique=False)
    op.create_index('pubsb_enms_q_id_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_enms_q_pubmid_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'pub_msg_id'], unique=True)
    op.create_index('pubsb_enms_q_subs_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'subscription_id'], unique=False)
    op.create_table('pubsub_endp_msg_q_inter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('inter_type', sa.String(length=200), nullable=False),
    sa.Column('inter_details', sa.Text(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], [u'pubsub_endp_msg_queue.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_enms_qi_endptp_idx', 'pubsub_endp_msg_q_inter', ['cluster_id', 'queue_id'], unique=False)
    op.create_index('pubsb_enms_qi_id_idx', 'pubsub_endp_msg_q_inter', ['cluster_id', 'id'], unique=True)
    op.drop_table('delivery_def_base')
    op.drop_table('delivery_def_out_wmq')
    op.drop_table('delivery')
    op.drop_table('delivery_history')
    op.drop_table('pub_sub_consumer')
    op.drop_table('pub_sub_producer')
    op.drop_table('delivery_payload')
    op.drop_table('pub_sub_topic')
    op.add_column('http_soap', sa.Column('cache_expiry', sa.Integer(), nullable=True))
    op.add_column('http_soap', sa.Column('cache_id', sa.Integer(), nullable=True))
    op.create_index('path_host_conn_act_clus_idx', 'http_soap', ['url_path', 'host', 'connection', 'soap_action', 'cluster_id'], unique=True)
    op.create_foreign_key(None, 'http_soap', 'cache', ['cache_id'], ['id'], ondelete=u'CASCADE')
    op.add_column('web_socket_client', sa.Column('cluster_id', sa.Integer(), nullable=False))
    op.drop_index('wscl_cli_ext_i_idx', table_name='web_socket_client')
    op.create_index('wscl_cli_ext_i_idx', 'web_socket_client', ['cluster_id', 'ext_client_id'], unique=False)
    op.drop_index('wscl_cli_ext_n_idx', table_name='web_socket_client')
    op.create_index('wscl_cli_ext_n_idx', 'web_socket_client', ['cluster_id', 'ext_client_name'], unique=False)
    op.drop_index('wscl_pr_addr_idx', table_name='web_socket_client')
    op.create_index('wscl_pr_addr_idx', 'web_socket_client', ['cluster_id', 'peer_address'], unique=False)
    op.drop_index('wscl_pr_fqdn_idx', table_name='web_socket_client')
    op.create_index('wscl_pr_fqdn_idx', 'web_socket_client', ['cluster_id', 'peer_fqdn'], unique=False)
    op.drop_index('wscl_pub_client_idx', table_name='web_socket_client')
    op.create_index('wscl_pub_client_idx', 'web_socket_client', ['cluster_id', 'pub_client_id'], unique=True)
    op.create_foreign_key(None, 'web_socket_client', 'cluster', ['cluster_id'], ['id'], ondelete=u'CASCADE')
    op.add_column('web_socket_sub', sa.Column('cluster_id', sa.Integer(), nullable=False))
    op.add_column('web_socket_sub', sa.Column('ext_client_id', sa.Text(), nullable=False))
    op.add_column('web_socket_sub', sa.Column('sub_key', sa.Text(), nullable=False))
    op.create_index('wssub_extcli_idx', 'web_socket_sub', ['cluster_id', 'ext_client_id'], unique=True)
    op.create_index('wssub_subkey_chan_idx', 'web_socket_sub', ['cluster_id', 'sub_key', 'channel_id'], unique=True)
    op.create_index('wssub_subkey_idx', 'web_socket_sub', ['cluster_id', 'sub_key'], unique=True)
    op.drop_index('wssub_channel_idx', table_name='web_socket_sub')
    op.create_index('wssub_channel_idx', 'web_socket_sub', ['cluster_id', 'channel_id'], unique=False)
    op.drop_index('wssub_patt_idx', table_name='web_socket_sub')
    op.drop_index('wssub_patt_is_idx', table_name='web_socket_sub')
    op.drop_constraint(None, 'web_socket_sub', type_='foreignkey')
    op.drop_constraint(None, 'web_socket_sub', type_='foreignkey')
    op.create_foreign_key(None, 'web_socket_sub', 'cluster', ['cluster_id'], ['id'], ondelete=u'CASCADE')
    op.drop_column('web_socket_sub', 'is_durable')
    op.drop_column('web_socket_sub', 'has_gd')
    op.drop_column('web_socket_sub', 'is_by_channel')
    op.drop_column('web_socket_sub', 'pattern')
    op.drop_column('web_socket_sub', 'server_id')
    op.drop_column('web_socket_sub', 'client_id')
    op.drop_column('web_socket_sub', 'is_by_ext_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_socket_sub', sa.Column('is_by_ext_id', sa.BOOLEAN(), nullable=False))
    op.add_column('web_socket_sub', sa.Column('client_id', sa.INTEGER(), nullable=True))
    op.add_column('web_socket_sub', sa.Column('server_id', sa.INTEGER(), nullable=True))
    op.add_column('web_socket_sub', sa.Column('pattern', sa.VARCHAR(length=400), nullable=False))
    op.add_column('web_socket_sub', sa.Column('is_by_channel', sa.BOOLEAN(), nullable=False))
    op.add_column('web_socket_sub', sa.Column('has_gd', sa.BOOLEAN(), nullable=False))
    op.add_column('web_socket_sub', sa.Column('is_durable', sa.BOOLEAN(), nullable=False))
    op.drop_constraint(None, 'web_socket_sub', type_='foreignkey')
    op.create_foreign_key(None, 'web_socket_sub', 'server', ['server_id'], ['id'])
    op.create_foreign_key(None, 'web_socket_sub', 'web_socket_client', ['client_id'], ['id'])
    op.create_index('wssub_patt_is_idx', 'web_socket_sub', ['pattern', 'is_internal', 'is_by_ext_id', 'is_by_channel'], unique=False)
    op.create_index('wssub_patt_idx', 'web_socket_sub', ['pattern'], unique=False)
    op.drop_index('wssub_channel_idx', table_name='web_socket_sub')
    op.create_index('wssub_channel_idx', 'web_socket_sub', ['channel_id'], unique=False)
    op.drop_index('wssub_subkey_idx', table_name='web_socket_sub')
    op.drop_index('wssub_subkey_chan_idx', table_name='web_socket_sub')
    op.drop_index('wssub_extcli_idx', table_name='web_socket_sub')
    op.drop_column('web_socket_sub', 'sub_key')
    op.drop_column('web_socket_sub', 'ext_client_id')
    op.drop_column('web_socket_sub', 'cluster_id')
    op.drop_constraint(None, 'web_socket_client', type_='foreignkey')
    op.drop_index('wscl_pub_client_idx', table_name='web_socket_client')
    op.create_index('wscl_pub_client_idx', 'web_socket_client', ['pub_client_id'], unique=1)
    op.drop_index('wscl_pr_fqdn_idx', table_name='web_socket_client')
    op.create_index('wscl_pr_fqdn_idx', 'web_socket_client', ['peer_fqdn'], unique=False)
    op.drop_index('wscl_pr_addr_idx', table_name='web_socket_client')
    op.create_index('wscl_pr_addr_idx', 'web_socket_client', ['peer_address'], unique=False)
    op.drop_index('wscl_cli_ext_n_idx', table_name='web_socket_client')
    op.create_index('wscl_cli_ext_n_idx', 'web_socket_client', ['ext_client_name'], unique=False)
    op.drop_index('wscl_cli_ext_i_idx', table_name='web_socket_client')
    op.create_index('wscl_cli_ext_i_idx', 'web_socket_client', ['ext_client_id'], unique=False)
    op.drop_column('web_socket_client', 'cluster_id')
    op.drop_constraint(None, 'http_soap', type_='foreignkey')
    op.drop_index('path_host_conn_act_clus_idx', table_name='http_soap')
    op.drop_column('http_soap', 'cache_id')
    op.drop_column('http_soap', 'cache_expiry')
    op.create_table('pub_sub_topic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('max_depth', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_payload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('creation_time', sa.DATETIME(), nullable=False),
    sa.Column('payload', sa.BLOB(), nullable=False),
    sa.Column('delivery_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], [u'delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_sub_producer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('sec_def_id', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ),
    sa.ForeignKeyConstraint(['sec_def_id'], [u'sec_base.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], [u'pub_sub_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_sub_consumer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('sub_key', sa.VARCHAR(length=200), nullable=False),
    sa.Column('max_depth', sa.INTEGER(), nullable=False),
    sa.Column('delivery_mode', sa.VARCHAR(length=200), nullable=False),
    sa.Column('callback_id', sa.INTEGER(), nullable=True),
    sa.Column('callback_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('sec_def_id', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['callback_id'], [u'http_soap.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ),
    sa.ForeignKeyConstraint(['sec_def_id'], [u'sec_base.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], [u'pub_sub_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('entry_time', sa.DATETIME(), nullable=False),
    sa.Column('entry_ctx', sa.BLOB(), nullable=False),
    sa.Column('resubmit_count', sa.INTEGER(), nullable=False),
    sa.Column('delivery_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], [u'delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('creation_time', sa.DATETIME(), nullable=False),
    sa.Column('args', sa.BLOB(), nullable=True),
    sa.Column('kwargs', sa.BLOB(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.Column('resubmit_count', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=200), nullable=False),
    sa.Column('source_count', sa.INTEGER(), nullable=False),
    sa.Column('target_count', sa.INTEGER(), nullable=False),
    sa.Column('definition_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], [u'delivery_def_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_def_out_wmq',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'delivery_def_base.id'], ),
    sa.ForeignKeyConstraint(['target_id'], [u'out_wmq.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_def_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('short_def', sa.VARCHAR(length=200), nullable=False),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=200), nullable=False),
    sa.Column('callback_list', sa.BLOB(), nullable=True),
    sa.Column('expire_after', sa.INTEGER(), nullable=False),
    sa.Column('expire_arch_succ_after', sa.INTEGER(), nullable=False),
    sa.Column('expire_arch_fail_after', sa.INTEGER(), nullable=False),
    sa.Column('check_after', sa.INTEGER(), nullable=False),
    sa.Column('retry_repeats', sa.INTEGER(), nullable=False),
    sa.Column('retry_seconds', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('pubsb_enms_qi_id_idx', table_name='pubsub_endp_msg_q_inter')
    op.drop_index('pubsb_enms_qi_endptp_idx', table_name='pubsub_endp_msg_q_inter')
    op.drop_table('pubsub_endp_msg_q_inter')
    op.drop_index('pubsb_enms_q_subs_idx', table_name='pubsub_endp_msg_queue')
    op.drop_index('pubsb_enms_q_pubmid_idx', table_name='pubsub_endp_msg_queue')
    op.drop_index('pubsb_enms_q_id_idx', table_name='pubsub_endp_msg_queue')
    op.drop_index('pubsb_enms_q_endptp_idx', table_name='pubsub_endp_msg_queue')
    op.drop_index('pubsb_enms_q_endp_idx', table_name='pubsub_endp_msg_queue')
    op.drop_table('pubsub_endp_msg_queue')
    op.drop_index('pubsb_endpt_msgid_idx', table_name='pubsub_endp_topic')
    op.drop_index('pubsb_endpt_id_idx', table_name='pubsub_endp_topic')
    op.drop_index('pubsb_endpt_clust_idx', table_name='pubsub_endp_topic')
    op.drop_index('pubsb_endpt_clsendtp_idx', table_name='pubsub_endp_topic')
    op.drop_table('pubsub_endp_topic')
    op.drop_index('pubsb_sub_id_idx', table_name='pubsub_sub')
    op.drop_index('pubsb_sub_clust_subk', table_name='pubsub_sub')
    op.drop_index('pubsb_sub_clust_idx', table_name='pubsub_sub')
    op.drop_index('pubsb_sub_clust_endpt_idx', table_name='pubsub_sub')
    op.drop_table('pubsub_sub')
    op.drop_index('pubsb_msg_pubmsg_id_idx', table_name='pubsub_message')
    op.drop_index('pubsb_msg_inreplyto_id_idx', table_name='pubsub_message')
    op.drop_index('pubsb_msg_id_idx', table_name='pubsub_message')
    op.drop_table('pubsub_message')
    op.drop_index('wscl_psk_sk', table_name='web_socket_cli_ps_keys')
    op.drop_index('wscl_psk_cli', table_name='web_socket_cli_ps_keys')
    op.drop_table('web_socket_cli_ps_keys')
    op.drop_index('pubsb_endp_name_idx', table_name='pubsub_endpoint')
    op.drop_index('pubsb_endp_id_idx', table_name='pubsub_endpoint')
    op.drop_index('pubsb_endp_clust_idx', table_name='pubsub_endpoint')
    op.drop_table('pubsub_endpoint')
    op.drop_index('pubsb_tp_name_idx', table_name='pubsub_topic')
    op.drop_index('pubsb_tp_id_idx', table_name='pubsub_topic')
    op.drop_index('pubsb_tp_clust_idx', table_name='pubsub_topic')
    op.drop_table('pubsub_topic')
    op.drop_table('cache_builtin')
    op.drop_table('cache_memcached')
    op.drop_table('cache')
    ### end Alembic commands ###
