"""migrate_from_2.0.8_to_5a7b9403

Revision ID: 0d1ac9c22670
Revises: 0028b_ae7849785be8
Create Date: 2017-12-14 15:35:05.578382

"""

# Revision identifiers, used by Alembic.
revision = '0029b_0d1ac9c22670'
down_revision = '0028b_ae7849785be8'

from alembic import context, op
import sqlalchemy as sa


# Zato
from zato.common.odb import model

# Pass this as a naming_convention= kwarg to batch_alter_table() in order to
# resolve unnamed constraint exceptions with SQLite. This is the default
# format used by PostgreSQL, it is likely if there are other databases to
# be supported, we will need to mimic their default naming behaviour by
# dynamically switching this at runtime, according to the driver in use.
naming_convention = {
    "fk": "%(table_name)s_%(column_0_name)s_fkey",
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_twilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('account_sid', sa.String(length=200), nullable=False),
    sa.Column('auth_token', sa.String(length=200), nullable=False),
    sa.Column('default_from', sa.String(length=200), nullable=True),
    sa.Column('default_to', sa.String(length=200), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('cache_type', sa.String(length=45), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('kv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.LargeBinary(), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=True),
    sa.Column('data_type', sa.String(length=200), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kv_data', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('key_clust_id_idx', ['key', 'cluster_id'], unique=True, mysql_length={u'key': 767})

    op.create_table('out_stomp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=200), server_default=u'guest', nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), server_default=u'localhost:61613', nullable=False),
    sa.Column('proto_version', sa.String(length=20), server_default=u'1.0', nullable=False),
    sa.Column('timeout', sa.Integer(), server_default='10', nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('cache_builtin',
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('max_item_size', sa.Integer(), nullable=False),
    sa.Column('extend_expiry_on_get', sa.Boolean(), nullable=False),
    sa.Column('extend_expiry_on_set', sa.Boolean(), nullable=False),
    sa.Column('sync_method', sa.String(length=20), nullable=False),
    sa.Column('persistent_storage', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['cache_id'], [u'cache.id'], ),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_table('channel_web_socket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('data_format', sa.String(length=20), nullable=False),
    sa.Column('new_token_wait_time', sa.Integer(), nullable=False),
    sa.Column('token_ttl', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], [u'sec_base.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'cluster_id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('pubsub_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('last_pub_time', sa.BigInteger(), nullable=True),
    sa.Column('max_depth_gd', sa.Integer(), nullable=False),
    sa.Column('max_depth_non_gd', sa.Integer(), nullable=False),
    sa.Column('current_depth_gd', sa.Integer(), nullable=False),
    sa.Column('gd_depth_check_freq', sa.Integer(), nullable=False),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('is_api_sub_allowed', sa.Boolean(), nullable=False),
    sa.Column('hook_service_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['hook_service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pubsub_topic', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('pubsb_tp_clust_idx', ['cluster_id'], unique=False)
        batch_op.create_index('pubsb_tp_id_idx', ['cluster_id', 'id'], unique=True)
        batch_op.create_index('pubsb_tp_name_idx', ['cluster_id', 'name'], unique=True)

    op.create_table('channel_stomp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=200), server_default=u'guest', nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), server_default=u'localhost:61613', nullable=False),
    sa.Column('proto_version', sa.String(length=20), server_default=u'1.0', nullable=False),
    sa.Column('timeout', sa.Integer(), server_default='10', nullable=False),
    sa.Column('sub_to', sa.Text(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('cache_memcached',
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('servers', sa.Text(), nullable=False),
    sa.Column('is_debug', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.LargeBinary(length=20000), nullable=True),
    sa.ForeignKeyConstraint(['cache_id'], [u'cache.id'], ),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_table('sec_jwt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'sec_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_socket_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('pub_client_id', sa.String(length=200), nullable=False),
    sa.Column('ext_client_id', sa.String(length=200), nullable=False),
    sa.Column('ext_client_name', sa.String(length=200), nullable=True),
    sa.Column('local_address', sa.String(length=400), nullable=False),
    sa.Column('peer_address', sa.String(length=400), nullable=False),
    sa.Column('peer_fqdn', sa.String(length=400), nullable=False),
    sa.Column('connection_time', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('server_proc_pid', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(length=200), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], [u'server.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_socket_client', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('wscl_cli_ext_i_idx', ['cluster_id', 'ext_client_id'], unique=False)
        batch_op.create_index('wscl_cli_ext_n_idx', ['cluster_id', 'ext_client_name'], unique=False)
        batch_op.create_index('wscl_pr_addr_idx', ['cluster_id', 'peer_address'], unique=False)
        batch_op.create_index('wscl_pr_fqdn_idx', ['cluster_id', 'peer_fqdn'], unique=False)
        batch_op.create_index('wscl_pub_client_idx', ['cluster_id', 'pub_client_id'], unique=True)

    op.create_table('web_socket_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('sub_key', sa.Text(), nullable=False),
    sa.Column('ext_client_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_socket_sub', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('wssub_channel_idx', ['cluster_id', 'channel_id'], unique=False)
        batch_op.create_index('wssub_extcli_idx', ['cluster_id', 'ext_client_id'], unique=True)
        batch_op.create_index('wssub_subkey_chan_idx', ['cluster_id', 'sub_key', 'channel_id'], unique=True)
        batch_op.create_index('wssub_subkey_idx', ['cluster_id', 'sub_key'], unique=True)

    op.create_table('pubsub_endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('endpoint_type', sa.String(length=40), nullable=False),
    sa.Column('last_seen', sa.BigInteger(), nullable=True),
    sa.Column('last_pub_time', sa.BigInteger(), nullable=True),
    sa.Column('last_sub_time', sa.BigInteger(), nullable=True),
    sa.Column('last_deliv_time', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('topic_patterns', sa.Text(), nullable=True),
    sa.Column('pub_tag_patterns', sa.Text(), nullable=True),
    sa.Column('message_tag_patterns', sa.Text(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('ws_channel_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], [u'sec_base.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['ws_channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'name'),
    sa.UniqueConstraint('cluster_id', 'security_id'),
    sa.UniqueConstraint('cluster_id', 'service_id'),
    sa.UniqueConstraint('cluster_id', 'ws_channel_id')
    )
    with op.batch_alter_table('pubsub_endpoint', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('pubsb_endp_clust_idx', ['cluster_id'], unique=False)
        batch_op.create_index('pubsb_endp_id_idx', ['cluster_id', 'id'], unique=True)
        batch_op.create_index('pubsb_endp_name_idx', ['cluster_id', 'name'], unique=True)

    op.create_table('sec_vault_conn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.Column('default_auth_method', sa.String(length=200), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('allow_redirects', sa.Boolean(), nullable=False),
    sa.Column('tls_verify', sa.Boolean(), nullable=False),
    sa.Column('tls_key_cert_id', sa.Integer(), nullable=True),
    sa.Column('tls_ca_cert_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'sec_base.id'], ),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['tls_ca_cert_id'], [u'sec_tls_ca_cert.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['tls_key_cert_id'], [u'sec_tls_key_cert.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pubsub_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_msg_id', sa.String(length=200), nullable=False),
    sa.Column('pub_correl_id', sa.String(length=200), nullable=True),
    sa.Column('in_reply_to', sa.String(length=200), nullable=True),
    sa.Column('ext_client_id', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('position_in_group', sa.Integer(), nullable=True),
    sa.Column('pattern_matched', sa.Text(), nullable=False),
    sa.Column('pub_time', sa.BigInteger(), nullable=False),
    sa.Column('ext_pub_time', sa.BigInteger(), nullable=True),
    sa.Column('expiration_time', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('data_prefix', sa.Text(), nullable=False),
    sa.Column('data_prefix_short', sa.String(length=200), nullable=False),
    sa.Column('data_format', sa.String(length=200), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.Integer(), nullable=False),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('published_by_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pubsub_message', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('pubsb_msg_id_idx', ['cluster_id', 'id'], unique=True)
        batch_op.create_index('pubsb_msg_inreplyto_id_idx', ['cluster_id', 'in_reply_to'], unique=False)
        batch_op.create_index('pubsb_msg_pubmsg_id_idx', ['cluster_id', 'pub_msg_id'], unique=True)

    op.create_table('web_socket_cli_ps_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_key', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], [u'web_socket_client.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_socket_cli_ps_keys', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('wscl_psk_cli', ['cluster_id', 'client_id'], unique=False)
        batch_op.create_index('wscl_psk_sk', ['cluster_id', 'sub_key'], unique=False)

    op.create_table('pubsub_endp_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_matched', sa.Text(), nullable=False),
    sa.Column('last_pub_time', sa.BigInteger(), nullable=False),
    sa.Column('pub_msg_id', sa.String(length=200), nullable=False),
    sa.Column('pub_correl_id', sa.String(length=200), nullable=True),
    sa.Column('in_reply_to', sa.String(length=200), nullable=True),
    sa.Column('ext_client_id', sa.Text(), nullable=True),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pubsub_endp_topic', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('pubsb_endpt_clsendtp_idx', ['cluster_id', 'endpoint_id', 'topic_id'], unique=True)
        batch_op.create_index('pubsb_endpt_clust_idx', ['cluster_id'], unique=False)
        batch_op.create_index('pubsb_endpt_id_idx', ['cluster_id', 'id'], unique=True)
        batch_op.create_index('pubsb_endpt_msgid_idx', ['cluster_id', 'pub_msg_id'], unique=True)

    op.create_table('pubsub_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.Column('sub_key', sa.String(length=200), nullable=False),
    sa.Column('pattern_matched', sa.Text(), nullable=False),
    sa.Column('deliver_by', sa.Text(), nullable=True),
    sa.Column('ext_client_id', sa.Text(), nullable=True),
    sa.Column('is_durable', sa.Boolean(), nullable=False),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('active_status', sa.String(length=200), nullable=False),
    sa.Column('is_staging_enabled', sa.Boolean(), nullable=False),
    sa.Column('delivery_method', sa.String(length=200), nullable=False),
    sa.Column('delivery_data_format', sa.String(length=200), nullable=False),
    sa.Column('delivery_endpoint', sa.Text(), nullable=True),
    sa.Column('last_interaction_time', sa.BigInteger(), nullable=True),
    sa.Column('last_interaction_type', sa.String(length=200), nullable=True),
    sa.Column('last_interaction_details', sa.Text(), nullable=True),
    sa.Column('delivery_batch_size', sa.Integer(), nullable=False),
    sa.Column('wrap_one_msg_in_list', sa.Boolean(), nullable=False),
    sa.Column('delivery_max_size', sa.Integer(), nullable=False),
    sa.Column('delivery_max_retry', sa.Integer(), nullable=False),
    sa.Column('delivery_err_should_block', sa.Boolean(), nullable=False),
    sa.Column('wait_sock_err', sa.Integer(), nullable=False),
    sa.Column('wait_non_sock_err', sa.Integer(), nullable=False),
    sa.Column('hook_service_id', sa.Integer(), nullable=True),
    sa.Column('out_http_method', sa.Text(), nullable=True),
    sa.Column('amqp_exchange', sa.Text(), nullable=True),
    sa.Column('amqp_routing_key', sa.Text(), nullable=True),
    sa.Column('files_directory_list', sa.Text(), nullable=True),
    sa.Column('ftp_directory_list', sa.Text(), nullable=True),
    sa.Column('sms_twilio_from', sa.Text(), nullable=True),
    sa.Column('sms_twilio_to_list', sa.Text(), nullable=True),
    sa.Column('smtp_subject', sa.Text(), nullable=True),
    sa.Column('smtp_from', sa.Text(), nullable=True),
    sa.Column('smtp_to_list', sa.Text(), nullable=True),
    sa.Column('smtp_body', sa.Text(), nullable=True),
    sa.Column('smtp_is_html', sa.Boolean(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('out_job_id', sa.Integer(), nullable=True),
    sa.Column('out_http_soap_id', sa.Integer(), nullable=True),
    sa.Column('out_smtp_id', sa.Integer(), nullable=True),
    sa.Column('out_amqp_id', sa.Integer(), nullable=True),
    sa.Column('ws_sub_id', sa.Integer(), nullable=True),
    sa.Column('ws_channel_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['hook_service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_amqp_id'], [u'out_amqp.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_http_soap_id'], [u'http_soap.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_job_id'], [u'job.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_smtp_id'], [u'email_smtp.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], [u'server.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['ws_channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['ws_sub_id'], [u'web_socket_sub.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pubsub_sub', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('pubsb_sub_clust_endpt_idx', ['cluster_id', 'endpoint_id', 'topic_id'], unique=False)
        batch_op.create_index('pubsb_sub_clust_idx', ['cluster_id'], unique=False)
        batch_op.create_index('pubsb_sub_clust_subk', ['cluster_id', 'sub_key'], unique=True)
        batch_op.create_index('pubsb_sub_id_idx', ['cluster_id', 'id'], unique=True)

    op.create_table('pubsub_endp_msg_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('last_delivery_time', sa.BigInteger(), nullable=True),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('is_in_staging', sa.Boolean(), nullable=False),
    sa.Column('is_deliverable', sa.Boolean(), nullable=False),
    sa.Column('delivery_status', sa.Text(), nullable=False),
    sa.Column('delivery_time', sa.BigInteger(), nullable=True),
    sa.Column('pub_msg_id', sa.String(length=200), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['pub_msg_id'], [u'pubsub_message.pub_msg_id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], [u'pubsub_sub.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pubsub_endp_msg_queue', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('pubsb_enms_q_endp_idx', ['cluster_id', 'endpoint_id'], unique=False)
        batch_op.create_index('pubsb_enms_q_endptp_idx', ['cluster_id', 'endpoint_id', 'topic_id'], unique=False)
        batch_op.create_index('pubsb_enms_q_id_idx', ['cluster_id', 'id'], unique=True)
        batch_op.create_index('pubsb_enms_q_pubmid_idx', ['cluster_id', 'pub_msg_id'], unique=True)
        batch_op.create_index('pubsb_enms_q_subs_idx', ['cluster_id', 'subscription_id'], unique=False)

    op.create_table('pubsub_endp_msg_q_inter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('inter_type', sa.String(length=200), nullable=False),
    sa.Column('inter_details', sa.Text(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], [u'pubsub_endp_msg_queue.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pubsub_endp_msg_q_inter', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_index('pubsb_enms_qi_endptp_idx', ['cluster_id', 'queue_id'], unique=False)
        batch_op.create_index('pubsb_enms_qi_id_idx', ['cluster_id', 'id'], unique=True)

    op.drop_table('delivery_def_base')
    op.drop_table('django_openid_auth_nonce')
    op.drop_table('delivery_payload')
    op.drop_table('django_openid_auth_useropenid')
    op.drop_table('delivery')
    op.drop_table('delivery_history')
    op.drop_table('pub_sub_topic')
    op.drop_table('pub_sub_consumer')
    op.drop_table('django_openid_auth_association')
    op.drop_table('pub_sub_producer')
    op.drop_table('delivery_def_out_wmq')
    with op.batch_alter_table('channel_amqp', schema=None, naming_convention=naming_convention, recreate="always") as batch_op:
        batch_op.add_column(sa.Column('ack_mode', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('pool_size', sa.Integer(), nullable=False))

    with op.batch_alter_table('channel_zmq', schema=None, naming_convention=naming_convention, recreate="always") as batch_op:
        batch_op.add_column(sa.Column('pool_strategy', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('service_source', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('socket_method', sa.String(length=20), nullable=False))

    with op.batch_alter_table('conn_def_amqp', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_column('def_type')

    with op.batch_alter_table('http_soap', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('cache_expiry', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cache_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sec_use_rbac', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index('path_host_conn_act_clus_idx', ['url_path', 'host', 'connection', 'soap_action', 'cluster_id'], unique=True)
        batch_op.create_foreign_key("http_soap_cache_id_fkey", 'cache', ['cache_id'], ['id'], ondelete=u'CASCADE')

    with op.batch_alter_table('out_amqp', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('pool_size', sa.SmallInteger(), nullable=False, server_default='1'))

    with op.batch_alter_table('out_zmq', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('socket_method', sa.String(length=20), nullable=False, server_default='connect'))

    with op.batch_alter_table('server', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('crypto_use_tls', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('preferred_address', sa.String(length=400), nullable=True))


def downgrade():
    raise NotImplementedError
