"""migrate_from_2.0.8_to_5a7b9403

Revision ID: 0d1ac9c22670
Revises: 0028b_ae7849785be8
Create Date: 2017-12-14 15:35:05.578382

"""

# Revision identifiers, used by Alembic.
revision = '0029b_0d1ac9c22670'
down_revision = '0028b_ae7849785be8'

from alembic import context, op
import sqlalchemy as sa

# Zato
from zato.common.odb import model

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('out_stomp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=200), server_default=u'guest', nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), server_default=u'localhost:61613', nullable=False),
    sa.Column('proto_version', sa.String(length=20), server_default=u'1.0', nullable=False),
    sa.Column('timeout', sa.Integer(), server_default='10', nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('sms_twilio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('account_sid', sa.String(length=200), nullable=False),
    sa.Column('auth_token', sa.String(length=200), nullable=False),
    sa.Column('default_from', sa.String(length=200), nullable=True),
    sa.Column('default_to', sa.String(length=200), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('kv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.LargeBinary(), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=True),
    sa.Column('data_type', sa.String(length=200), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('key_clust_id_idx', 'kv_data', ['key', 'cluster_id'], unique=True, mysql_length={u'key': 767})
    op.create_table('cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('cache_type', sa.String(length=45), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('cache_builtin',
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('max_item_size', sa.Integer(), nullable=False),
    sa.Column('extend_expiry_on_get', sa.Boolean(), nullable=False),
    sa.Column('extend_expiry_on_set', sa.Boolean(), nullable=False),
    sa.Column('sync_method', sa.String(length=20), nullable=False),
    sa.Column('persistent_storage', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['cache_id'], [u'cache.id'], ),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_table('cache_memcached',
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('servers', sa.Text(), nullable=False),
    sa.Column('is_debug', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.LargeBinary(length=20000), nullable=True),
    sa.ForeignKeyConstraint(['cache_id'], [u'cache.id'], ),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_table('channel_web_socket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('data_format', sa.String(length=20), nullable=False),
    sa.Column('new_token_wait_time', sa.Integer(), nullable=False),
    sa.Column('token_ttl', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], [u'sec_base.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'cluster_id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('pubsub_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('last_pub_time', sa.BigInteger(), nullable=True),
    sa.Column('max_depth_gd', sa.Integer(), nullable=False),
    sa.Column('max_depth_non_gd', sa.Integer(), nullable=False),
    sa.Column('current_depth_gd', sa.Integer(), nullable=False),
    sa.Column('gd_depth_check_freq', sa.Integer(), nullable=False),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('is_api_sub_allowed', sa.Boolean(), nullable=False),
    sa.Column('hook_service_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['hook_service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_tp_clust_idx', 'pubsub_topic', ['cluster_id'], unique=False)
    op.create_index('pubsb_tp_id_idx', 'pubsub_topic', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_tp_name_idx', 'pubsub_topic', ['cluster_id', 'name'], unique=True)
    op.create_table('channel_stomp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=200), server_default=u'guest', nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), server_default=u'localhost:61613', nullable=False),
    sa.Column('proto_version', sa.String(length=20), server_default=u'1.0', nullable=False),
    sa.Column('timeout', sa.Integer(), server_default='10', nullable=False),
    sa.Column('sub_to', sa.Text(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'cluster_id')
    )
    op.create_table('sec_jwt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'sec_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sec_vault_conn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.Column('default_auth_method', sa.String(length=200), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('allow_redirects', sa.Boolean(), nullable=False),
    sa.Column('tls_verify', sa.Boolean(), nullable=False),
    sa.Column('tls_key_cert_id', sa.Integer(), nullable=True),
    sa.Column('tls_ca_cert_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'sec_base.id'], ),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['tls_ca_cert_id'], [u'sec_tls_ca_cert.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['tls_key_cert_id'], [u'sec_tls_key_cert.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('web_socket_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('pub_client_id', sa.String(length=200), nullable=False),
    sa.Column('ext_client_id', sa.String(length=200), nullable=False),
    sa.Column('ext_client_name', sa.String(length=200), nullable=True),
    sa.Column('local_address', sa.String(length=400), nullable=False),
    sa.Column('peer_address', sa.String(length=400), nullable=False),
    sa.Column('peer_fqdn', sa.String(length=400), nullable=False),
    sa.Column('connection_time', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('server_proc_pid', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(length=200), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], [u'server.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('wscl_cli_ext_i_idx', 'web_socket_client', ['cluster_id', 'ext_client_id'], unique=False)
    op.create_index('wscl_cli_ext_n_idx', 'web_socket_client', ['cluster_id', 'ext_client_name'], unique=False)
    op.create_index('wscl_pr_addr_idx', 'web_socket_client', ['cluster_id', 'peer_address'], unique=False)
    op.create_index('wscl_pr_fqdn_idx', 'web_socket_client', ['cluster_id', 'peer_fqdn'], unique=False)
    op.create_index('wscl_pub_client_idx', 'web_socket_client', ['cluster_id', 'pub_client_id'], unique=True)
    op.create_table('web_socket_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('sub_key', sa.Text(), nullable=False),
    sa.Column('ext_client_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('wssub_channel_idx', 'web_socket_sub', ['cluster_id', 'channel_id'], unique=False)
    op.create_index('wssub_extcli_idx', 'web_socket_sub', ['cluster_id', 'ext_client_id'], unique=True)
    op.create_index('wssub_subkey_chan_idx', 'web_socket_sub', ['cluster_id', 'sub_key', 'channel_id'], unique=True)
    op.create_index('wssub_subkey_idx', 'web_socket_sub', ['cluster_id', 'sub_key'], unique=True)
    op.create_table('pubsub_endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('endpoint_type', sa.String(length=40), nullable=False),
    sa.Column('last_seen', sa.BigInteger(), nullable=True),
    sa.Column('last_pub_time', sa.BigInteger(), nullable=True),
    sa.Column('last_sub_time', sa.BigInteger(), nullable=True),
    sa.Column('last_deliv_time', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('topic_patterns', sa.Text(), nullable=True),
    sa.Column('pub_tag_patterns', sa.Text(), nullable=True),
    sa.Column('message_tag_patterns', sa.Text(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('ws_channel_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], [u'sec_base.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['ws_channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'name'),
    sa.UniqueConstraint('cluster_id', 'security_id'),
    sa.UniqueConstraint('cluster_id', 'service_id'),
    sa.UniqueConstraint('cluster_id', 'ws_channel_id')
    )
    op.create_index('pubsb_endp_clust_idx', 'pubsub_endpoint', ['cluster_id'], unique=False)
    op.create_index('pubsb_endp_id_idx', 'pubsub_endpoint', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_endp_name_idx', 'pubsub_endpoint', ['cluster_id', 'name'], unique=True)
    op.create_table('pubsub_endp_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_matched', sa.Text(), nullable=False),
    sa.Column('last_pub_time', sa.BigInteger(), nullable=False),
    sa.Column('pub_msg_id', sa.String(length=200), nullable=False),
    sa.Column('pub_correl_id', sa.String(length=200), nullable=True),
    sa.Column('in_reply_to', sa.String(length=200), nullable=True),
    sa.Column('ext_client_id', sa.Text(), nullable=True),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_endpt_clsendtp_idx', 'pubsub_endp_topic', ['cluster_id', 'endpoint_id', 'topic_id'], unique=True)
    op.create_index('pubsb_endpt_clust_idx', 'pubsub_endp_topic', ['cluster_id'], unique=False)
    op.create_index('pubsb_endpt_id_idx', 'pubsub_endp_topic', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_endpt_msgid_idx', 'pubsub_endp_topic', ['cluster_id', 'pub_msg_id'], unique=True)
    op.create_table('pubsub_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_msg_id', sa.String(length=200), nullable=False),
    sa.Column('pub_correl_id', sa.String(length=200), nullable=True),
    sa.Column('in_reply_to', sa.String(length=200), nullable=True),
    sa.Column('ext_client_id', sa.Text(), nullable=True),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('position_in_group', sa.Integer(), nullable=True),
    sa.Column('pattern_matched', sa.Text(), nullable=False),
    sa.Column('pub_time', sa.BigInteger(), nullable=False),
    sa.Column('ext_pub_time', sa.BigInteger(), nullable=True),
    sa.Column('expiration_time', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('data_prefix', sa.Text(), nullable=False),
    sa.Column('data_prefix_short', sa.String(length=200), nullable=False),
    sa.Column('data_format', sa.String(length=200), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('expiration', sa.Integer(), nullable=False),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('published_by_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_msg_id_idx', 'pubsub_message', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_msg_inreplyto_id_idx', 'pubsub_message', ['cluster_id', 'in_reply_to'], unique=False)
    op.create_index('pubsb_msg_pubmsg_id_idx', 'pubsub_message', ['cluster_id', 'pub_msg_id'], unique=True)
    op.create_table('web_socket_cli_ps_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_key', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], [u'web_socket_client.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('wscl_psk_cli', 'web_socket_cli_ps_keys', ['cluster_id', 'client_id'], unique=False)
    op.create_index('wscl_psk_sk', 'web_socket_cli_ps_keys', ['cluster_id', 'sub_key'], unique=False)
    op.create_table('pubsub_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.Column('sub_key', sa.String(length=200), nullable=False),
    sa.Column('pattern_matched', sa.Text(), nullable=False),
    sa.Column('deliver_by', sa.Text(), nullable=True),
    sa.Column('ext_client_id', sa.Text(), nullable=True),
    sa.Column('is_durable', sa.Boolean(), nullable=False),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('active_status', sa.String(length=200), nullable=False),
    sa.Column('is_staging_enabled', sa.Boolean(), nullable=False),
    sa.Column('delivery_method', sa.String(length=200), nullable=False),
    sa.Column('delivery_data_format', sa.String(length=200), nullable=False),
    sa.Column('delivery_endpoint', sa.Text(), nullable=True),
    sa.Column('last_interaction_time', sa.BigInteger(), nullable=True),
    sa.Column('last_interaction_type', sa.String(length=200), nullable=True),
    sa.Column('last_interaction_details', sa.Text(), nullable=True),
    sa.Column('delivery_batch_size', sa.Integer(), nullable=False),
    sa.Column('wrap_one_msg_in_list', sa.Boolean(), nullable=False),
    sa.Column('delivery_max_size', sa.Integer(), nullable=False),
    sa.Column('delivery_max_retry', sa.Integer(), nullable=False),
    sa.Column('delivery_err_should_block', sa.Boolean(), nullable=False),
    sa.Column('wait_sock_err', sa.Integer(), nullable=False),
    sa.Column('wait_non_sock_err', sa.Integer(), nullable=False),
    sa.Column('hook_service_id', sa.Integer(), nullable=True),
    sa.Column('out_http_method', sa.Text(), nullable=True),
    sa.Column('amqp_exchange', sa.Text(), nullable=True),
    sa.Column('amqp_routing_key', sa.Text(), nullable=True),
    sa.Column('files_directory_list', sa.Text(), nullable=True),
    sa.Column('ftp_directory_list', sa.Text(), nullable=True),
    sa.Column('sms_twilio_from', sa.Text(), nullable=True),
    sa.Column('sms_twilio_to_list', sa.Text(), nullable=True),
    sa.Column('smtp_subject', sa.Text(), nullable=True),
    sa.Column('smtp_from', sa.Text(), nullable=True),
    sa.Column('smtp_to_list', sa.Text(), nullable=True),
    sa.Column('smtp_body', sa.Text(), nullable=True),
    sa.Column('smtp_is_html', sa.Boolean(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('out_job_id', sa.Integer(), nullable=True),
    sa.Column('out_http_soap_id', sa.Integer(), nullable=True),
    sa.Column('out_smtp_id', sa.Integer(), nullable=True),
    sa.Column('out_amqp_id', sa.Integer(), nullable=True),
    sa.Column('ws_sub_id', sa.Integer(), nullable=True),
    sa.Column('ws_channel_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['hook_service_id'], [u'service.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_amqp_id'], [u'out_amqp.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_http_soap_id'], [u'http_soap.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_job_id'], [u'job.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['out_smtp_id'], [u'email_smtp.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], [u'server.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['ws_channel_id'], [u'channel_web_socket.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['ws_sub_id'], [u'web_socket_sub.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_sub_clust_endpt_idx', 'pubsub_sub', ['cluster_id', 'endpoint_id', 'topic_id'], unique=False)
    op.create_index('pubsb_sub_clust_idx', 'pubsub_sub', ['cluster_id'], unique=False)
    op.create_index('pubsb_sub_clust_subk', 'pubsub_sub', ['cluster_id', 'sub_key'], unique=True)
    op.create_index('pubsb_sub_id_idx', 'pubsub_sub', ['cluster_id', 'id'], unique=True)
    op.create_table('pubsub_endp_msg_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.BigInteger(), nullable=False),
    sa.Column('delivery_count', sa.Integer(), nullable=False),
    sa.Column('last_delivery_time', sa.BigInteger(), nullable=True),
    sa.Column('has_gd', sa.Boolean(), nullable=False),
    sa.Column('is_in_staging', sa.Boolean(), nullable=False),
    sa.Column('is_deliverable', sa.Boolean(), nullable=False),
    sa.Column('delivery_status', sa.Text(), nullable=False),
    sa.Column('delivery_time', sa.BigInteger(), nullable=True),
    sa.Column('pub_msg_id', sa.String(length=200), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], [u'pubsub_endpoint.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['pub_msg_id'], [u'pubsub_message.pub_msg_id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], [u'pubsub_sub.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], [u'pubsub_topic.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_enms_q_endp_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'endpoint_id'], unique=False)
    op.create_index('pubsb_enms_q_endptp_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'endpoint_id', 'topic_id'], unique=False)
    op.create_index('pubsb_enms_q_id_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'id'], unique=True)
    op.create_index('pubsb_enms_q_pubmid_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'pub_msg_id'], unique=True)
    op.create_index('pubsb_enms_q_subs_idx', 'pubsub_endp_msg_queue', ['cluster_id', 'subscription_id'], unique=False)
    op.create_table('pubsub_endp_msg_q_inter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('inter_type', sa.String(length=200), nullable=False),
    sa.Column('inter_details', sa.Text(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['queue_id'], [u'pubsub_endp_msg_queue.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pubsb_enms_qi_endptp_idx', 'pubsub_endp_msg_q_inter', ['cluster_id', 'queue_id'], unique=False)
    op.create_index('pubsb_enms_qi_id_idx', 'pubsub_endp_msg_q_inter', ['cluster_id', 'id'], unique=True)
    op.drop_table('delivery_def_base')
    op.drop_table('django_openid_auth_nonce')
    op.drop_table('delivery_payload')
    op.drop_table('django_openid_auth_useropenid')
    op.drop_table('delivery')
    op.drop_table('delivery_history')
    op.drop_table('pub_sub_topic')
    op.drop_table('pub_sub_consumer')
    op.drop_table('django_openid_auth_association')
    op.drop_table('pub_sub_producer')
    op.drop_table('delivery_def_out_wmq')
    op.add_column('channel_amqp', sa.Column('ack_mode', sa.String(length=20), nullable=False))
    op.add_column('channel_amqp', sa.Column('pool_size', sa.Integer(), nullable=False))
    op.add_column('channel_zmq', sa.Column('pool_strategy', sa.String(length=20), nullable=False))
    op.add_column('channel_zmq', sa.Column('service_source', sa.String(length=20), nullable=False))
    op.add_column('channel_zmq', sa.Column('socket_method', sa.String(length=20), nullable=False))
    op.drop_column('conn_def_amqp', 'def_type')
    op.add_column('http_soap', sa.Column('cache_expiry', sa.Integer(), nullable=True))
    op.add_column('http_soap', sa.Column('cache_id', sa.Integer(), nullable=True))
    op.add_column('http_soap', sa.Column('content_type', sa.String(length=200), nullable=True))
    op.add_column('http_soap', sa.Column('sec_use_rbac', sa.Boolean(), nullable=False))
    op.create_index('path_host_conn_act_clus_idx', 'http_soap', ['url_path', 'host', 'connection', 'soap_action', 'cluster_id'], unique=True)
    op.create_foreign_key(None, 'http_soap', 'cache', ['cache_id'], ['id'], ondelete=u'CASCADE')
    op.add_column('out_amqp', sa.Column('pool_size', sa.SmallInteger(), nullable=False))
    op.add_column('out_zmq', sa.Column('socket_method', sa.String(length=20), nullable=False))
    op.add_column('server', sa.Column('crypto_use_tls', sa.Boolean(), nullable=True))
    op.add_column('server', sa.Column('preferred_address', sa.String(length=400), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'preferred_address')
    op.drop_column('server', 'crypto_use_tls')
    op.drop_column('out_zmq', 'socket_method')
    op.drop_column('out_amqp', 'pool_size')
    op.drop_constraint(None, 'http_soap', type_='foreignkey')
    op.drop_index('path_host_conn_act_clus_idx', table_name='http_soap')
    op.drop_column('http_soap', 'sec_use_rbac')
    op.drop_column('http_soap', 'content_type')
    op.drop_column('http_soap', 'cache_id')
    op.drop_column('http_soap', 'cache_expiry')
    op.add_column('conn_def_amqp', sa.Column('def_type', sa.VARCHAR(length=10), nullable=False))
    op.drop_column('channel_zmq', 'socket_method')
    op.drop_column('channel_zmq', 'service_source')
    op.drop_column('channel_zmq', 'pool_strategy')
    op.drop_column('channel_amqp', 'pool_size')
    op.drop_column('channel_amqp', 'ack_mode')
    op.create_table('delivery_def_out_wmq',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'delivery_def_base.id'], ),
    sa.ForeignKeyConstraint(['target_id'], [u'out_wmq.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_sub_producer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('sec_def_id', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ),
    sa.ForeignKeyConstraint(['sec_def_id'], [u'sec_base.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], [u'pub_sub_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_openid_auth_association',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('handle', sa.VARCHAR(length=255), nullable=False),
    sa.Column('secret', sa.VARCHAR(length=255), nullable=False),
    sa.Column('issued', sa.INTEGER(), nullable=False),
    sa.Column('lifetime', sa.INTEGER(), nullable=False),
    sa.Column('assoc_type', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_sub_consumer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('sub_key', sa.VARCHAR(length=200), nullable=False),
    sa.Column('max_depth', sa.INTEGER(), nullable=False),
    sa.Column('delivery_mode', sa.VARCHAR(length=200), nullable=False),
    sa.Column('callback_id', sa.INTEGER(), nullable=True),
    sa.Column('callback_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('topic_id', sa.INTEGER(), nullable=False),
    sa.Column('sec_def_id', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['callback_id'], [u'http_soap.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ),
    sa.ForeignKeyConstraint(['sec_def_id'], [u'sec_base.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], [u'pub_sub_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_sub_topic',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('max_depth', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=64), nullable=False),
    sa.Column('entry_time', sa.DATETIME(), nullable=False),
    sa.Column('entry_ctx', sa.BLOB(), nullable=False),
    sa.Column('resubmit_count', sa.INTEGER(), nullable=False),
    sa.Column('delivery_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], [u'delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('creation_time', sa.DATETIME(), nullable=False),
    sa.Column('args', sa.BLOB(), nullable=True),
    sa.Column('kwargs', sa.BLOB(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.Column('resubmit_count', sa.INTEGER(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=200), nullable=False),
    sa.Column('source_count', sa.INTEGER(), nullable=False),
    sa.Column('target_count', sa.INTEGER(), nullable=False),
    sa.Column('definition_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], [u'delivery_def_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_openid_auth_useropenid',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('claimed_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('display_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_payload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('creation_time', sa.DATETIME(), nullable=False),
    sa.Column('payload', sa.BLOB(), nullable=False),
    sa.Column('delivery_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], [u'delivery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('django_openid_auth_nonce',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('server_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.Column('salt', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_def_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('short_def', sa.VARCHAR(length=200), nullable=False),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.Column('target_type', sa.VARCHAR(length=200), nullable=False),
    sa.Column('callback_list', sa.BLOB(), nullable=True),
    sa.Column('expire_after', sa.INTEGER(), nullable=False),
    sa.Column('expire_arch_succ_after', sa.INTEGER(), nullable=False),
    sa.Column('expire_arch_fail_after', sa.INTEGER(), nullable=False),
    sa.Column('check_after', sa.INTEGER(), nullable=False),
    sa.Column('retry_repeats', sa.INTEGER(), nullable=False),
    sa.Column('retry_seconds', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], [u'cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('pubsb_enms_qi_id_idx', table_name='pubsub_endp_msg_q_inter')
    op.drop_index('pubsb_enms_qi_endptp_idx', table_name='pubsub_endp_msg_q_inter')
    op.drop_table('pubsub_endp_msg_q_inter')
    op.drop_index('pubsb_enms_q_subs_idx', table_name='pubsub_endp_msg_queue')
    op.drop_index('pubsb_enms_q_pubmid_idx', table_name='pubsub_endp_msg_queue')
    op.drop_index('pubsb_enms_q_id_idx', table_name='pubsub_endp_msg_queue')
    op.drop_index('pubsb_enms_q_endptp_idx', table_name='pubsub_endp_msg_queue')
    op.drop_index('pubsb_enms_q_endp_idx', table_name='pubsub_endp_msg_queue')
    op.drop_table('pubsub_endp_msg_queue')
    op.drop_index('pubsb_sub_id_idx', table_name='pubsub_sub')
    op.drop_index('pubsb_sub_clust_subk', table_name='pubsub_sub')
    op.drop_index('pubsb_sub_clust_idx', table_name='pubsub_sub')
    op.drop_index('pubsb_sub_clust_endpt_idx', table_name='pubsub_sub')
    op.drop_table('pubsub_sub')
    op.drop_index('wscl_psk_sk', table_name='web_socket_cli_ps_keys')
    op.drop_index('wscl_psk_cli', table_name='web_socket_cli_ps_keys')
    op.drop_table('web_socket_cli_ps_keys')
    op.drop_index('pubsb_msg_pubmsg_id_idx', table_name='pubsub_message')
    op.drop_index('pubsb_msg_inreplyto_id_idx', table_name='pubsub_message')
    op.drop_index('pubsb_msg_id_idx', table_name='pubsub_message')
    op.drop_table('pubsub_message')
    op.drop_index('pubsb_endpt_msgid_idx', table_name='pubsub_endp_topic')
    op.drop_index('pubsb_endpt_id_idx', table_name='pubsub_endp_topic')
    op.drop_index('pubsb_endpt_clust_idx', table_name='pubsub_endp_topic')
    op.drop_index('pubsb_endpt_clsendtp_idx', table_name='pubsub_endp_topic')
    op.drop_table('pubsub_endp_topic')
    op.drop_index('pubsb_endp_name_idx', table_name='pubsub_endpoint')
    op.drop_index('pubsb_endp_id_idx', table_name='pubsub_endpoint')
    op.drop_index('pubsb_endp_clust_idx', table_name='pubsub_endpoint')
    op.drop_table('pubsub_endpoint')
    op.drop_index('wssub_subkey_idx', table_name='web_socket_sub')
    op.drop_index('wssub_subkey_chan_idx', table_name='web_socket_sub')
    op.drop_index('wssub_extcli_idx', table_name='web_socket_sub')
    op.drop_index('wssub_channel_idx', table_name='web_socket_sub')
    op.drop_table('web_socket_sub')
    op.drop_index('wscl_pub_client_idx', table_name='web_socket_client')
    op.drop_index('wscl_pr_fqdn_idx', table_name='web_socket_client')
    op.drop_index('wscl_pr_addr_idx', table_name='web_socket_client')
    op.drop_index('wscl_cli_ext_n_idx', table_name='web_socket_client')
    op.drop_index('wscl_cli_ext_i_idx', table_name='web_socket_client')
    op.drop_table('web_socket_client')
    op.drop_table('sec_vault_conn')
    op.drop_table('sec_jwt')
    op.drop_table('channel_stomp')
    op.drop_index('pubsb_tp_name_idx', table_name='pubsub_topic')
    op.drop_index('pubsb_tp_id_idx', table_name='pubsub_topic')
    op.drop_index('pubsb_tp_clust_idx', table_name='pubsub_topic')
    op.drop_table('pubsub_topic')
    op.drop_table('channel_web_socket')
    op.drop_table('cache_memcached')
    op.drop_table('cache_builtin')
    op.drop_table('cache')
    op.drop_index('key_clust_id_idx', table_name='kv_data')
    op.drop_table('kv_data')
    op.drop_table('sms_twilio')
    op.drop_table('out_stomp')
    ### end Alembic commands ###
